name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Create static build directory
        run: mkdir -p _site
      - name: Copy static content to build directory
        run: |
          # Copy the HTML templates to the site root
          cp -r glitchwebapp/templates/* _site/
          # Copy static assets
          mkdir -p _site/static
          cp -r glitchwebapp/static/* _site/static/ || echo "No static files to copy"
          # Ensure we have an index.html
          if [ ! -f _site/index.html ]; then
            cp -f index.html _site/index.html
          fi
          # Replace Django template tags with static content
          find _site -type f -name "*.html" -exec sed -i 's/{% extends.*%}//g' {} \;
          find _site -type f -name "*.html" -exec sed -i 's/{% load.*%}//g' {} \;
          find _site -type f -name "*.html" -exec sed -i 's/{% block.*%}//g' {} \;
          find _site -type f -name "*.html" -exec sed -i 's/{% endblock.*%}//g' {} \;
          find _site -type f -name "*.html" -exec sed -i 's/{% static \(.*\) %}/static\/\1/g' {} \;
          find _site -type f -name "*.html" -exec sed -i 's/{% url \(.*\) %}/\1.html/g' {} \;
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
